<header>
        <nav>
            <a href="index.php"><img src="images/logo.jpeg" alt="logo" class="logo"></a>
            <label><span class="material-symbols-outlined">
                search
                </span><input class="search" type="text" placeholder="Search.." ></label>
                <select id="pageSelector">
                    <option>Select Option....</option>
                     <option value="index.php">Home</option>
                     <option value="facilities.php">Facilities</option>
                    <option value="add.php">Add</option>
                    <option value="gallery.php">Gallery</option>
                </select>
                
        </nav>
    </header>